### ISSUE TITLE
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by jupitern** [ratchetphp/Ratchet#1002]
PHP 8.1

strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated on /var/www/app/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php line 88

stacktrace:
"#1 /var/www/app/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(88): strpos()",
"#2 /var/www/app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\\Server\\IoServer->handleConnect()",
"#3 /var/www/app/vendor/react/socket/src/SocketServer.php(72): Evenement\\EventEmitter->emit()",
"#4 /var/www/app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\\Socket\\SocketServer->React\\Socket\\{closure}()",
"#5 /var/www/app/vendor/react/socket/src/TcpServer.php(255): Evenement\\EventEmitter->emit()",
"#6 /var/www/app/vendor/react/socket/src/TcpServer.php(235): React\\Socket\\TcpServer->handleConnection()",
"#7 /var/www/app/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\\Socket\\TcpServer->React\\Socket\\{closure}()",
"#8 /var/www/app/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\\EventLoop\\StreamSelectLoop->waitForStreamActivity()",
"#9 /var/www/app/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\\EventLoop\\StreamSelectLoop->run()"

**Comment by SimonFrings** [comment]
I'm currently working on testing this project against PHP 8.0, PHP 8.1 and PHP 8.2, so I opened up a ticket to post my progress in, see #1003.

**Comment by clue** [comment]
@jupitern Please take the time to properly report issues. I'm not sure what you're reporting is a bug or issue in this project, so I can only assume this is related to #1003 and will close this for now. Please report back and add more details otherwise.

**Comment by Gkiokan** [comment]
It is probably only a deprecation warning that spams the logs full on each call. 
Probably.

The issue happens on this [IoServer.php:88](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IoServer.php#L88).

And can be probably fixed by adding an alternative fallback to the `$uri` variable before.  
But this would be just a quick fix to stop the deprecation warnings, as everything seems to work fine. 
Change this from:
```
        $uri = $conn->getRemoteAddress();
```

to
```
        $uri = $conn->getRemoteAddress() ?? '';
````

The more correct way would be to debug down why `$conn->getRemoteAddress()` returns null instead of any valid address.
