### ISSUE TITLE
client os still waiting until the previous script finished

### ISSUE THREAD

**Issue by jhay06** [ratchetphp/Ratchet#1020]
i noticed that . when i have a long running process then when i run a new script while the long running process is still running  . the last script will receive response once the long process script is done  

let say

function test(){
 client.send("starting");
 while(true){ 
// long running
}
 client.send(“done“);

}

expectation:  the message starting will receive by the client before the long running script will start its job and then afterwards it will receive the message done once the job is done

behavior: the client still wait for the long running script and then after the job is done . the word starting anf the word done were both receive in the same time . 

any thoughts?

**Comment by SimonFrings** [comment]
Hey @jhay06, are you sure this is the right place for this? From what I'm seeing, this doesn't look like PHP or Ratchet to me.

I'm not convinced that this is currently related to Ratchet, please understand that this is what we're trying to focus our support on here. If you can proof this problem only occurs when working with this project, please provide information about what steps you tried, what worked and what didn't, and we'll take a closer look.

**Comment by jhay06** [comment]
hi @SimonFrings  , this is purely related to ratchet , and i'm using the example from https://www.twilio.com/blog/create-php-websocket-server-build-real-time-even-driven-application.   it is a blog that create a sample websocket using ratchet ,

and the parts where ratchet is blocking is from this part 
![image](https://github.com/ratchetphp/Ratchet/assets/5191437/dd2f541d-cd93-4ed3-91de-1df1f5503f7e)



i add while loop from there , to check how it goes when a client call a message

**Comment by SimonFrings** [comment]
Thanks for the additional information @jhay06 :+1:

If you would execute this in a blocking environment, this would be the right thing to do, but you're seeing this behavior due to the async and non-blocking nature of underlying ReactPHP. When you call `$client->send("hello first call");` it doesn't immediately send your message, it first tells an event-loop to execute this at the next possible time (like adding it to a queue). This sometimes takes "some time" as the operation might need a little longer to be ready to run, so we want to be efficient and execute the next line while waiting for `send()` to be ready. This will now trigger the `while()` loop which will block your code until it's finish, so the situation you're seeing here is:

1. The event-loop is waiting for the next opportunity to send the message "hello first call".
2. The `while()` blocks the event-loop, so we have to wait until its finished.
3. We now have time to send "hello first call" and we'll also send "done" right after as this is the next in line.

This means you want to avoid anything blocking in this async environment, of course this depends on what your use case is. If you want to take a deeper look at the async utils of ReactPHP, you can look into https://github.com/reactphp/async or https://github.com/reactphp/promise. You can also use https://github.com/reactphp/child-process to run the blocking processes while the rest can stay purely non-blocking.

Hope this helps :+1:
