### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by sibprogrammer** [ratchetphp/Ratchet#1025]
@cboden, could you clarify the project status, please? It looks abandoned, and according to the code frequency chart, the activity has declined to 0 during the last 5-6 years, but a lot of people still use the project, and it requires maintenance and future improvements.
Maybe it's a good option to transfer the ownership if someone is ready to continue the maintenance. As far as I can see, @clue and @SimonFrings had some thoughts about that.
I started one more fork here: https://github.com/plesk/ratchetphp, and fixed a bunch of things to make it compatible and testable on PHP 8.x. At some point, I realized keeping it as a fork made no sense and detached it. There are a lot of stuck pull requests here, and adding several more would not help anybody. 
I'll be glad to collaborate, but the project status is unclear, and it looks abandoned.

**Comment by SimonFrings** [comment]
Hey @sibprogrammer, this is actually a complicated situation here, so I'll try to give you a quick overview.

We're aware about the status of Ratchet and we really want to change some things in here, this includes supporting the latest (PHP) versions, improving the project documentation, answer/review open issue & pull requests, and much more. 

So in a gist we know what to do with Ratchet, the problem is that we have to find the time to actually do it. A few years back I decided to make Open Source my job, means I'm investing a lot of time into maintaining projects like ReactPHP, Framework X and others. While Open Source itself doesn't pay the bills (yet), I also help other developers and companies achieving their goals with their projects. This constellation takes up most of my team's time and priorities, and doesn't really allow us to invest time into Ratchet currently (it's sad to say, but it is a tradeoff).

I'm always on the lookout for opportunities to create a overlap between our business interest and our Open Source interest, that's one of the reasons my work with clients mostly involves ReactPHP. This worked pretty great for us in the past and I can see this as a great opportunity to get Ratchet back on track Ratchet.



So as you can see half of my time goes into consulting and the other half into 

This is of course easier said than done.

Working on Open Source is part o our 

Working on Open Source is not just something we do in our free-

We're putting a  lot of our work into maintaining ReactPHP, Framework X and other projects here in GitHub while also 

Easier said than done, maintaining ReactPHP, Framework X already takes up time. Made Open Source to our job/Job resolves around Open Source, of course Open Source itself doesn't pay the bills, so we cover this through working together with developers (consulting), helping maintain commercial projects.

Always looking for opportunities to find some overlap between a companies interest and Open Source work.

A lot to do, bring up to newest versions, way more documentation needed, answering/reviewing amount of tickets, etc.

**Comment by newmediacrew** [comment]
Did they remove the comment previously posted ?

**Comment by clue** [comment]
Hey @sibprogrammer, this is a very interesting question, so I'll try to give you some overview.

We're aware of the current status of Ratchet and we really want to move forward with improving some things in here, this includes supporting the latest (PHP) versions (https://github.com/ratchetphp/Ratchet/issues/1003), improving the project documentation, answer/review open issue & pull requests, and much more. I'm working on this together with @SimonFrings to answer issues & pull request in here when time allows, but there's still a lot to do. So in a gist, we know what to do with Ratchet, the problem is that we have to find the time to *actually do* it.

Some time ago, I made the decision to make open source my job. This means that I invest a significant amount of time into maintaining projects like ReactPHP, Framework X, and others nowadays. While open source itself may not directly pay the bills at the moment, I also have the opportunity to help various developers and companies achieve their goals with their projects through my consulting service. This arrangement currently occupies most of my team's time and priorities, which unfortunately limits our ability to invest more time into Ratchet at the moment (as much as I'd like to see this change in the future!).

I am constantly seeking opportunities to align our open source endeavors with business interests to ensure we can focus on our open source work to benefit the entire community. That's why my paid work primarily involves ReactPHP and related projects, which has proven to be successful for us over the years. Likewise, I can see this would be a great chance to bring Ratchet back on track if there's enough interest in moving forward with the project.

I see you're actively working on your fork in the @Plesk organization on GitHub, and I believe this could be a wonderful chance to collaborate and join forces. Definitely also seeing some huge wins for the larger ecosystem if we can make sure Ratchet works seamlessly with Plesk.

Apologies for the lengthy explanation, but I figured you might be interested in some of the details behind the scenes. If you're interested in working together with us, shoot me an email and I'm sure we will get the ball rolling again and make Ratchet even more awesome!

*(Started writing this reply a couple of days ago but had to shift focus, please ignore the incomplete draft of this message that we accidentally sent a few days ago)*

**Comment by hayden-t** [comment]
@sibprogrammer i looked at your fork, what autobahn version does it work with ? or do you use a different or custom js client library ?

**Comment by rupeshstha** [comment]
So sad to hear, another awesome package is not getting updated 2 years from now! Hope this awesome package gets justice. 🙂🤞

**Comment by clue** [comment]
> Is the project abandoned?

No, it is not 🎉 Please help us revive Ratchet and let's give Ratchet the love it deserves! See #1054 for follow-up.
