### ISSUE TITLE
Ratchet Website Installation Page is Wrong

### ISSUE THREAD

**Issue by macfisher** [ratchetphp/Ratchet#272]
Gents,

I am trying to get started with using Ratchet for the first time.  The Installation instructions that you provide say to:
1. Download and install composer, done.
2. Create a file called composer.json and "copy and paste the JSON code at the top of the page"...
There is no JSON code at the top of the page.  I do not want to move on with an empty composer.json file.  Hopefully you can provide some JSON code so I can use this.  Thank you.

**Comment by cboden** [comment]
whoops. Part of the documentation was recently updated to the reflect the way composer now recommends to install libraries. Once you have composer installed run this command (assuming composer.phar is in your home directory):
```bash
php ~/composer.phar require cboden/ratchet
```

And then you're done!

**Comment by macfisher** [comment]
Thank you so much for getting back to me so fast.  The install instructions make more sense now.  As soon as I update my PHP version to 5.3.9 I can use this.  Thanks again and I look forward to getting this all up and running.

**Comment by RemoRemovich** [comment]
Hi, cboden!

I'm trying to install ratchet on my web-hosting - jino.ru . 

I downloaded composer.phar to my website's directory, but when I run 
/usr/bin/php5.6 composer.phar require cboden/ratchet
I get this error message:

[Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:
  php ~/composer.phar
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

I don't have composer.json in my website directory, that's why I get this message. So, I think composer.json is still necessary to install Ratchet in my case.

Can you please recommend a suitable composer.json file content or any other way to install Ratchet on my web-hosting?

Thank you any way!

**Comment by cboden** [comment]
@RemoRemovich Try running `composer self-update` before `composer require cboden/ratchet`. I just did so and managed to successfully install Ratchet.
