### ISSUE TITLE
Accessing the WAMP session ID from a connection object

### ISSUE THREAD

**Issue by tpavlek** [ratchetphp/Ratchet#282]
I have a WAMP application implementing the `WampServerInterface`. My use case is I want to "catch up" users who have just subscribed. If a user subscribes to a topic - say, `chat_messages` - then I want to send that user the last five chat messages. Obviously I don't want to broadcast these to the whole topic, just that specific user.

My implementation would be to, onSubscribe, send that information to the user using their sessionId as a whitelist. Since the WampInterface onSubscribe has a signature `(ConnectionInterface $conn, $topic)` I need to be taking a `ConnectionInterface`, which doesn't expose any information about the underlying connection.

In code, I can do `$conn->wrappedConn->WAMP->sessionId` and get the sessionId, however since my code is relying on an interface, and the interface doesn't expose that method this feels like an inflexible piece of code that could easily break in the future.

Are my assumptions about any of this wrong, and should I be doing it a better way? Am I nervous about nothing? Or does it make sense that there should be a method on ConnectionInterface to enable this use-case?

**Comment by ProPheT777** [comment]
To do not broadcast for all user, just check out the method definition. https://github.com/ratchetphp/Ratchet/blob/d00102cb3926a5731b73c5878ec7beafb9dc4a93/src/Ratchet/Wamp/Topic.php#L46

**Comment by cboden** [comment]
Just an update - we ended discussing this on IRC shortly after the issue was opened. 

Currently `$conn->wrappedConn->WAMP->sessionId` is the recommended way to access this. It's not ideal from a type hint perspective but the decorator architecture of Ratchet allows for this type of flexibility; it is up to the App to require a component interface that will alter `ConnectionInterface` appropriately.
