### ISSUE TITLE
Private chat, Message logging to mysql DB and Session retaining

### ISSUE THREAD

**Issue by kirensiva** [ratchetphp/Ratchet#296]
I implemented a private chat and is working fine. It is implemented like mentioned here https://github.com/ratchetphp/Ratchet/issues/261. 
This is my current implementation
1) User register in my app with a username.
2) User login (1st and 2nd step through core php)
3) Once user logged in successfully
	a) opens the web socket connection
	b) then send a message containing his username
	c) this username and his resourceId is send to all other online users (notification) 
	d)their UI is updated to reflect the new user.
	e) New user UI is updated with all other users too
       	f) When he select a user and send the message it will be delivered to the selected user only.
So far working fine. 
But
1) Is this correct way to implement private chat system?
2) What should I do if I want to log the incoming and out going messages to mysql db. (https://github.com/ratchetphp/Ratchet/issues/145 )
3) What should I do to retain the session even if the user refreshed the page. (currently close the connection)
4) How can I use session provider? From the doc http://socketo.me/docs/sessions. Session is getting like $conn->Session->get('name’);
<?php
    // Inside your MyApp class
    public function onOpen($conn) {
        $conn->send('Hello ' . $conn->Session->get('name'));
    }
But from where should I set it like  $session->set('name’)? If you say after login How to do this with session provider ? I know native session will not work?
Please help me :)

**Comment by cboden** [comment]
> 1) Is this correct way to implement private chat system?

If it works it is correct  :-)  My personal recommendation is to use the WAMP protocol and create topics with a random GUID that only the participants chatting are aware of. This message pattern should make things easier. 

> 2) What should I do if I want to log the incoming and out going messages to mysql db. (#145 )

I would suggest using a PSR-4 logger and pipe your messages to a React ChildProcess script that will insert into your MySQL database. This will prevent your script from blocking.

> 3) What should I do to retain the session even if the user refreshed the page. (currently close the connection)

Give you're using my suggestion from (1) when the client re-connects have them re-subscribe to the same GUID instead of asking for a new one. They will both retain the channel and continue speaking within that topic session.

> 4) How can I use session provider? From the doc http://socketo.me/docs/sessions. Session is getting like $conn->Session->get('name’);

The SessionProvider is very primitive right now. It can only read from the database once when a connection is established and holds that data in memory. It could become stale over time and you can not write to it. A better implementation is planned in the future, but it's a ways off.

**Comment by kirensiva** [comment]
Thank you for the detailed reply. I will revert you...

**Comment by tonix-tuft** [comment]
@cboden Regarding the blocking nature of MySQL queries when using standard PHP components (like `PDO`).
When using Ratchet, what would you suggest in order to authenticate a WebSocket connection if you need to check if the connection is allowed against a MySQL table? I have the connection token within a cookie which in the `public function onOpen(ConnectionInterface $conn) {` Ratchet's hook:

```
...
public function onOpen(ConnectionInterface $conn) {
    $HTTPRequest = $conn->httpRequest;
    $cookies = parseCookiesFromHTTPRequest($HTTPRequest); // Returns associative array with cookies (name => value).

    // Now, I would need to allow the connection if $cookies['token'] is not empty
    // and it exists in a MySQL table.
    // But I shouldn't use a PDO instance because it would block the script
    // until the row is retrieved from the table.
    // The paradox is that I also need to know now if the connection is allowed or not,
    // because if it is not allowed, I would call `$conn->close()` and force it to close.

    // How can I overcome this while still adhering to the philosophy of React PHP and Ratchet (make I/O unblocking)?
}
...
```

**Comment by tonix-tuft** [comment]
Nevermind, I find it out how to deal with this using promises!
