### ISSUE TITLE
/docs/install is obsolete

### ISSUE THREAD

**Issue by Tilogorn** [ratchetphp/Ratchet#304]
Your install-page (http://socketo.me/docs/install) is outdated. I just started my first Ratchet project and the installation instructions were quite confusing.
1. Composer installs itself as a binary in the path now (at least on Windows), so the new command would be: `composer require cboden/ratchet` (succesfully tested on Windows 8). Found out in [this answer on Stackoverflow](http://stackoverflow.com/questions/21670709/could-not-open-input-file-composer-phar-error-in-symfony2-using-wamp#answer-22586674). Also there is no more the need for the `composer install` command, the files are automatically loaded (with the first command).
2. Your ["Wait, What?"-section](http://socketo.me/docs/install#waitwhat) speaks of "JSON from the top of this page" and a few other outdated instructions. Just look again over this text.

**Comment by cboden** [comment]
Good catches. Indeed the recommended installation path has changed since the socketo.me install docs were written. Also, section one was updated without consideration of two. @Tilogorn would you be willing to open a PR on [reactphp/socketo.me](https://github.com/ratchetphp/socketo.me) to fix the documentation?

**Comment by Tilogorn** [comment]
I'm no native speaker, but I'll try my best :-)
