### ISSUE TITLE
Websocket server stop responding after some hours.

### ISSUE THREAD

**Issue by pradeepta20** [ratchetphp/Ratchet#328]
Hello. I have used the supervisor concept to check and restart my chat server if it is stopped.

After some time interval my chat not working.When i check the console i didn't find any websocket connection fail error.

Then i use below command to check my server is running or not and see the server still running.

ps aux | grep php

So i am confused where is the issue or bug for which my chat application not working.

**Comment by pradeepta20** [comment]
When i kill the chat server process manually by using the "kill" command then the supervisor start the chat server immediately and my chat working fine.

**Comment by cboden** [comment]
Put the following code in your script and restart it:
```php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

Please paste the output of the following command here:

    composer show -i

Once the error happens again don't kill the script. Check and paste the latest output of the supervisor stdout and error logs in this issue.

Once the error has happened ssh directly into the server and run the `telnet` command and enter the following into it (and paste the output here):

    GET / HTTP/1.1
    Host: localhost

**Comment by rohitkhatri** [comment]
I'm going through the same problem.

and here is what was shown on "composer show -i" command

cboden/ratchet           v0.3.3 PHP WebSocket library
evenement/evenement      v2.0.0 Événement is a very simple event dispatching library for PHP
guzzle/common            v3.9.2 Common libraries used by Guzzle
guzzle/http              v3.9.2 HTTP libraries used by Guzzle
guzzle/parser            v3.9.2 Interchangeable parsers used by Guzzle
guzzle/stream            v3.9.2 Guzzle stream wrapper component
react/event-loop         v0.4.1 Event loop abstraction layer that libraries can use for evented I/O.
react/socket             v0.4.2 Library for building an evented socket server.
react/stream             v0.4.2 Basic readable and writable stream interfaces that support piping.
react/zmq                v0.3.0 ZeroMQ bindings for React.
symfony/event-dispatcher v2.7.1 Symfony EventDispatcher Component
symfony/http-foundation  v2.7.1 Symfony HttpFoundation Component
symfony/routing          v2.7.1 Symfony Routing Component

I placed these statements at the starting of my server file, but didn't find any.

error_reporting(E_ALL);
ini_set('display_errors', 1);

please help me.

**Comment by cboden** [comment]
@rohitkhatri What happens when you do the telnet thing after the server has stopped responding?

**Comment by cboden** [comment]
Closing due to extended period of inactivity. I'll re-open if reporting continues.

**Comment by Chaosvex** [comment]
Slightly late to the party but I've been looking into Ratchet again and I wanted to check to see if some of the issues that I encountered last time I tried to use (two years ago) have been resolved. 

This particular issue was a showstopper when it came to using Ratchet for a service that ran continuously and I'm seeing a fair number of reports here with similar symptoms. Ratchet would work fine for a while before becoming unresponsive to new connections, maxing out the CPU and needing restarted. Initially, it'd run happily for several weeks but that ended dropping to needing manual intervention every couple of days.

The problem turned out to be that it's leaking file descriptors and as soon as it hits the maximum (1024 by default, I believe), restarting the process would be required. As the site's traffic grew, it'd end up hitting the limit quicker. I didn't have the time or interest fix the root of the problem on a hobby project so I can't offer up a patch but perhaps being aware that there was/is a leak can help get the ball rolling.

**Comment by pinumanu** [comment]
pradeepta20 .. got any solution for that...

**Comment by pradeepta20** [comment]
Initially i have done the database coding using PDO.Later i change the code to mysqli its working fine for me.
I don't know the exact reason but it was due to some database coding error.

**Comment by pradeepta20** [comment]
Use below code to connect automatically when Websocket server restarted.

var wsUri;

$(function() { 
    wsUri = $("ws_uri").val();
    init();
}); 
function init() { 
    websocket = new WebSocket(wsUri);      
    websocket.onopen = function(ev) { //connection is open                 
    }   
    websocket.onmessage = function(ev) {           
    };    
    websocket.onerror	= function(ev){   
    }; 
    websocket.onclose = function(ev) {
        init();
    };  
}

**Comment by MarcGodard** [comment]
I am having a similar issue. The web browser doesn't connect (but it doesnt fail either) and hen I check the websocket logs, everything looks fine and the new connection isn't started. My sockets are basic without a database.

**Comment by cboden** [comment]
@Chaosvex The file descriptor limit issue is an operating system level feature...you will run into this problem with any language/environment (not just Ratchet/PHP). If you're hosting a WebSocket server 1024 is WAY too low if you expect any traffic at all. 

@MarcGodard Please follow the directions from [this comment above](https://github.com/ratchetphp/Ratchet/issues/328#issuecomment-112089958) and report the output so we can help troubleshoot.

**Comment by Chaosvex** [comment]
@cboden Yes, I know that but that has nothing to do with the leaks within Ratchet.

**Comment by MarcGodard** [comment]
@cboden I figured out the issue minutes after posting that. It was my fault. Thanks for the quick responce.

**Comment by andig** [comment]
@MarcGodard could you share your finding if its of general interest?

**Comment by MarcGodard** [comment]
I had an error in my code, that's all.

**Comment by Vendin** [comment]
The same problem as at @pradeepta20, in several hours sockets cease to answer. In this discussion I haven't found the solution. Whether there is a solution in general, except as restart of sockets constantly?

**Comment by tahir-grappetite** [comment]
I'm using AWS EC2 server for my application. My chat has stopped 2 times till now automatically but when I go to terminal and use the pgrep command to find the websocket process, its showing me processes, its mean that socket is connected to server. but still chat was not working. Then i kill all two process mnually and my cron job which is set for every 1 minute to start socket its running again and my chat get live again. I faced this issue 2 times. I don't know how things are going on in the background. I didn't find any logs, I have maintained all the logs that user is attached, user msg to this user, blah blah. but there is no error log in my logs.

Further more if mobile user just turned off his/her wifi or mobile data my chat is not firing onClose method. So the thing is that how to mark a user offline in this scenario if someone met this criteria. Which is the way to mark user offline if onClose method not fired.

Thanks!

**Comment by cmycmyu2** [comment]
This issue may caused by this error: "Fatal error: Allowed memory size of xxxxxx bytes exhausted (tried to allocate xxxxxx bytes) in ....."

Solution:
Increase the value of memory_limit in php.ini.

**Comment by Chaosvex** [comment]
Considering that neither developer has responded to a showstopper of a bug in several years, you'd be best dropping this project and looking for an alternative.

**Comment by WyriHaximus** [comment]
We fixed several memory leaks in ReactPHP over the last few years since your last comment. We implemented new event loops and done a ton of performance upgrades. The thing is you need to account for the following when deploying:

* Raise ulimit for your user/application so it can handle more then 1024 open FD's 
* Use an event loop extension over the default stream select loop which is hard capped at 1024 FD's
* Monitor your application's connections, memory usage, CPU usage, request/messages per second

we simple cannot debug very deeply into your problem without information like that. But what also matters is what you do when a connection has been establisht, what kind of resources you use and how you connect to databases/storage etc etc.

And last I really want to stress that we cannot change the 1024 thing for you on your deployment. You have to do that yourself. It's baked in hardcoded into `stream_select` and you need to change the event loop and raise it on ulimit if you want to resolve that. Wheither or not you consider raising the limit a good solution, that is how the OS works, it's entirely out of our hands and into yours to resolve that on your systems.

**Comment by Chaosvex** [comment]
This was never about memory leaks or even a concurrent handle/descriptor limit, it was about the descriptors leaking so a popular Ratchet-based site would have to be frequently killed off and restarted to prevent it from live-locking and potentially bringing an entire system to a crawl. Concurrent handles was irrelevant.

**Comment by WyriHaximus** [comment]
File descriptors don't leak, and according to your own description hitting the 1024 limit was/is the root cause of the issue you where having. They can leak over from a parent process into a child process but that's a totally different issue. (And we added tooling against that in `react/child-process` [v0.6.0](https://github.com/reactphp/child-process/releases/tag/v0.6.0).)

The thing is we have several users doing more then 50K+ connections in a single process with Ratchet without a hitch. And I don't want to suggest the problem is within your code, but implementing a long running service in PHP is a delicate dance between us the maintainers of Ratchet/ReactPHP and the implementer's of our libraries. This is also on a lower level PHP then your normal request-response cycle. I gladly sit down for a hangouts call with anyone to resolve their problems, but it's going to get technical and diving into tracing, logging and monitoring really fast. And to be really honest I can't do much with "It's locking up please fix". I want to dive into that and preferably try and find a way to reproduce it so we can fix it up stream.

Personally I monitor the memory usage (amongst things) fanatically to stay ahead of issues like this. 

![image](https://user-images.githubusercontent.com/147145/54046609-31bfbe80-41d5-11e9-9f8e-74dfb24a3e14.png)

**Comment by Chaosvex** [comment]
Yes, hitting 1024 *total* over the lifetime of the process, not 1024 concurrent. When those connections are no longer active and there's no longer a handle available, that's when it comes a leak.

**Comment by cboden** [comment]
Just tested this with StreamSelectLoop, no problems. I suspect you're holding a reference somewhere, holding open 1024 connections, causing your problems. 

`composer require cboden/ratchet`
```php
<?php
    require __DIR__ . '/vendor/autoload.php';

    $app = new Ratchet\App('localhost', 8080);
    $app->route('/echo', new Ratchet\Server\EchoServer, array('*'));
    $app->run();
```
```javascript
// In a browser
setInterval(() => {
  let c = new WebSocket('ws://localhost:8080/echo');
  setTimeout(() => c.close(), 250);
}, 500);
```

<img width="293" alt="screen shot 2019-03-08 at 2 11 47 pm" src="https://user-images.githubusercontent.com/617694/54050014-299f5900-41ac-11e9-9886-4c06042b1fe8.png">

---

^ Server still responding with 101 HTTP status code after 1024 connections.

**Comment by inri13666** [comment]
Given example implements variant with closed connections
What about not closed connections
I'm failed after 125 connections
with 
```
var x = []; for(var i=0; i<1024; i++) {x[i] = new WebSocket('ws://MYHOSTADDERSS/ws');}
```

**Comment by cboden** [comment]
@inri13666 What's the error you're getting? The reason I closed connections was because the browser I was testing with didn't allow that many concurrent connections to a single server as a security measure.

**Comment by inri13666** [comment]
I do not have any errors in the log, the socket not responding and only socket command restart may help :(

**Comment by inri13666** [comment]
I found the cause for my issue,
### Web browsers allow huge numbers of open WebSockets
The infamous 6 connections per host limit does not apply to WebSockets. Instead a far bigger limit holds (255 in Chrome and 200 in Firefox).

https://cs.chromium.org/chromium/src/net/socket/client_socket_pool_manager.cc?q=WEBSOCKET_SOCKET_POOL&sq=package:chromium&type=cs&l=29

**Comment by inri13666** [comment]
Totally I found the final solution
Never use `React\EventLoop\StreamSelectLoop` this is the cause of all issue on Linux it's limited to 1023 connections on windows it fails after 512

To solve the issue described here install one of the following PHP extensions

1. [Event extension](https://pecl.php.net/package/event) _My Choice, but for windows, have some [issues](https://github.com/reactphp/event-loop/issues/189)_
2. [libuv wrapper](https://pecl.php.net/package/uv) _This loop is known to work PHP 7+._
3. [interface to libev library](https://pecl.php.net/package/ev) _This loop is known to work with PHP 5.4 through PHP 7+._
4. [Libevent - event notification](https://pecl.php.net/package/libevent) _Not recommended for PHP 7+_ but have An [unofficial update](https://github.com/php/pecl-event-libevent/pull/2)
5. [PHP libev Extension](https://github.com/m4rw3r/php-libev)

P/S
Sample application to check connections
Server: https://github.com/inri13666/web-socket-echoserver
Client: https://github.com/inri13666/web-socket-test

**Comment by machomath** [comment]
Hi I am sorry for this late comment. I was having a similar issue that server seemingly stopped responding after some time. Tried many solutions but at the end turned out that MySQL was taking timeout after 8 hours of inactivity and disconnecting. So I put a root cron job 
0 0,8,16 * * * systemctl restart abc.service
It worked for me.

**Comment by nivshah** [comment]
I know this issue is quite old and has been closed for a while but it best covers what I have been running into.

Every once a while, my websocket message interface just stops working/responding. I restart the server and things immediately work again, with clients immediately reconnecting. Sometimes it breaks again within 10 or so minutes and sometimes it works for hours or days without any issue. I have a cronjob that restarts this server every 3 hours, so my question is:

Is there determinism on which PECL extension (ev, event) is used whenever the websocket loop is defined? Is there a chance that sometimes I'm getting a loop that uses one interface and sometimes I get the other if I have both PECL extensions installed?

I do not see any memory or CPU issues on the server, but whenever I see a series of broken pipe issues:

`An error has occurred: Unable to write to stream: fwrite(): SSL: Broken pipe`

I restart and either don't see these errors again or do, in which case I restart again until they subside.

**Comment by abbaasi69** [comment]
I had an experience which may help somebody.
My server was stoping responding after one hour when the number of concurrent socket connections reached about 700. After doing all of the possible solutions, I realized that I had a ProxyPass in apache which redirects port 443 (SSL) to 8080 (my socket port). Finally, I increased the ServerLimit in my Apache prefork configuration from 700 to 1700 and the problem was solved temporarily.
This shows that if you use ProxyPass of Apache (or another webserver) the Apache will become busy as it is between the client and WebSocket server.

**Comment by roguitar88** [comment]
Well, folks, I dunno quite well whether my issue has something to do with one in specific... However, this is what I've experienced for practically one month or so: I have a websocket service running via supervisor on port 8080, and it works perfectly with my code implementation (PHP/Javascript/Codeigniter)... Yes, it works well, but just until PAST 10 OR 12 HOURS (GENERALLY THE FOLLOWING DAY). When I'm gonna check the websocket service itself, okay, it's there... Running on port 8080, okay... The issue seems to be on client side (at least apparently, because I also suspect that there may be some hinder on server side). Checking my console (Javascript logs), and I see that:
1. It really connects (onopen is fired)
2. onmessage works
3. But... when the algorhythm tries to do anything with websocket.send(), the connection is closed immediately (note: onerror() is not fired, but onclose()). This happens on client side (browser)
4. I have ev (installed via pecl) installed and running there, I did it yesterday, but the issue seems to persist.
5. I'm using OriginCheck, but I believe it has no relation at all with the issue
6. In Ningx, I'm using a server block similar to this:

```
  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
  }

  upstream ws-backend {             
      # server websocket.your-site.com:8080;       
      # server localhost:8080;            
      # server 135.659.25.124:8080;
      server 127.0.0.1:8080; #leave only this, if localhost
  }

#If you want to force HTTPS, use the server block below:
  server {
      listen 80;
      listen [::]:80;

      server_name websocket.your-site.com

      return 301 https://$host$request_uri;
  }

  server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      server_name websocket.your-site.com;

      #Start the SSL configurations
      #ssl on;
      ssl_protocols TLSv1.2;

      # Fix The Logjam Attack.
      ssl_ciphers EECDH+AESGCM:EDH+AE...; #only for example purposes
      ssl_prefer_server_ciphers on;
      ssl_dhparam /etc/ssl/dh2048_param.pem;
      
      ssl_certificate /etc/pathto/websocket.your-site.com/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/pathto/websocket.your-site.com/privkey.pem; # managed by Certbot
      
      location / {
          proxy_set_header       X-Forwarded-For $remote_addr;
          proxy_set_header       Host $http_host;
          proxy_pass             http://ws-backend;
          proxy_http_version     1.1;
          proxy_set_header       Upgrade $http_upgrade;
          proxy_set_header       Connection $connection_upgrade;
      }
  }
```

7. As you can see above, I created a subdomain just for the websocket thing. and I'm using `Connection $connection_upgrade` always. If I use `Connection ""`, I simply will not be able to connect to the websocket any longer, it outputs: `WebSocket connection to 'wss://websocket.your-site.com/' failed:`. But... Of course, this doesn't have anything to do with the issue either
8.  In nginx.conf, I set `worker_processes auto;`,  `worker_rlimit_nofile 500000;`, `worker_connections 1024;`... At least so far... But I think those numbers are more than enough
9. I checked the file descriptors limit and I solved to increase (absurdly) some values: `fs.file-max = 2097152` there in /etc/sysctl.conf, `root hard nofile 500000`, `oot soft nofile 500000`, there in /etc/security/limits.conf, `session required pam_limits.so` there in /etc/pam.d/common-session
10. I'm using PDO and the database connection settings have been placed inside the construct method of the websocket app main class
10. These are server specs: 16GB RAM, 400GB SSD, 6vCPU cores, 32TB bandwidth (unlimited incoming traffic)
11. In sum, I just dunno what on Earth is causing this. In truth, I can't take it any longer, lol.

**Comment by amirlegendesk** [comment]
in 2023 I am also facing same issue. Nothing in logs, no errors but after few hours the messages are not sent.
