### ISSUE TITLE
Ratchet Server in HA?

### ISSUE THREAD

**Issue by fedyfausto** [ratchetphp/Ratchet#359]
Is there a way to share or to put the list of opened sockets somewhere so as to develop a distributed server ? For exemple i use an Array where i put my ConnectionInterface when a client connect to the server and check that for control if the user is online or not. Now i wanna make HA (active) servers with Ratchet but the only problem is that... any solution? THX a lot :)

**Comment by manixabrat** [comment]
Just an idea - you could create a centralized point from which you start servers, could also be a separate WS server as far as it matters, which will hold a record of which servers are running or connections to them all if that is not overkill.

**Comment by filirnd** [comment]
Manixabrat i like this idea but how we can enter into a data structure when we keep connetionInterface objects from different ws server ?

**Comment by manixabrat** [comment]
Well that is not really possible since resources are limited to the scope of the script, however you can build an additional level of abstraction where you would be able to push and pull data from the stack of servers. In the idea I proposed the controlling unit should be able to query servers about its clients, assuming all clients have a common identifying mechanism then you would be able to figure out which connection is which client and via the other part of the abstraction layer (push), you would be able to tell the server in question to push data to the client you desire.

**Comment by kinncj** [comment]
Why not pub/sub?
Using redis or even RabbitMQ you could dispatch an event when a connection was made:
`user.connected` and the listeners could easily receive the event on a method and increase its counter.

```PHP
/** pseudo code **/
class YourWS
{
    private $onlineUsers = 0;

    public function onOpen(Object $object)
    {
         /** ... **/

          $rabbitMQConnection->publish('user.connected', $id); //pseudo
    }

    public function onClose(Object $object)
    {
        /** ... **/

        $rabbitMQConnection->publish('user.disconnected', $id); //pseudo
    }

    /** these are the methods subscribed to a channel/queue/exchange/whatever **/

    public function onConnected(Envelope $envelope)
    {
        $this->onlineUsers++;
    }

    public function onDisconnected(Envelope $envelope)
    {
        $this->onlineUsers--;
    }
}
```

Just ***google*** `php redis pub/sub` or `php rabbitmq consumer`

You could even implement your own sessionhandler to store the session in redis/riak/whatever and share the same session between the nodes, so when you receive the `event` with a given `UserID` you could easily fetch its informations that are probably stored in the session.
