### ISSUE TITLE
Difference between manual wrap and using Ratchet\App

### ISSUE THREAD

**Issue by shirofuji** [ratchetphp/Ratchet#372]
Hello Ratchet Dev,

I would like to ask if there is difference in performance when using manual wrapping (i.e. the one found on socketo.me tutorials in push integration), and using the Ratchet\App class. Both seems to work fine but I haven't been able to observe their performance very well.

**Comment by cboden** [comment]
There would be a negligible performance decrease using `App` simply because it does a bit more than the tutorials. I'd suggest checking the [`App`'s source code](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/App.php). It uses the same decorating classes from the tutorials internally in addition to basic security and routing.
