### ISSUE TITLE
Binary feature

### ISSUE THREAD

**Issue by Xaraknid** [ratchetphp/Ratchet#393]
I see that your library missing binary feature.
Here a little cheatsheet for enabling binary.

Binary message bypass UTF-8 checking.
You'll need to have 2 variables : 
CurrentFrameOpcode 
FirstFrameOpcode ( when frame opcode are 0 to know if your messsage are TEXT or BINARY )

Add event ->onBinary ( seem better for dev user ) or 
add opcode in ->onMessage

Your send method are allready well formed for sending binary ( last variable )

**Comment by cboden** [comment]
The messaging handlers of the lib actually handle binary messages already the API just doesn't provide indicators. 

v0.4 is almost in beta which will include updates to the API to include binary message sending and receiving. The API code hans't been published yet but you can checkout the change to the [`Message class`](https://github.com/ratchetphp/RFC6455/blob/psr7-multi-streamer/src/Messaging/Protocol/Message.php#L115) 

The API is *probably* going to look something like this (in order to not have an API break):
```php
function onMessage(ConnectionInterface $conn, $msg, $isBinary);
function send($msg, $isBinary);
```

I haven't decided yet if $msg will be the `Message` object (which now has a `__toString` method) or just the payload string. 

For the next version I may overhaul the component architecture interfaces to be cleaner and more OO.

**Comment by Xaraknid** [comment]
That great news and sorry for duplicate.  Maybe I oversee it but is it possible to send CONTINUOUS frame from apps to let dev  send fragmented message?

**Comment by cboden** [comment]
It's do-able, just not obvious. When you do `$conn->send($msg)` you can send it a `FrameInterface`. `Message`s and `Frame`s implement `FrameInterface` so you can build your own messages via `Frame`s that are `CONTINUE` frames. 

I try to find a balance between simple/easy interfaces where users can deal with just `send(string)` and flexibility where power users can do things like send fragmented messages.

**Comment by Xaraknid** [comment]
Ok i see. If I may suggest something It'll be better to have 2 differents event to split binary from text.  Simply to prevent break code of dev who only deal with TEXT but a client send BINARY data if dev didn't check that data they are dealing are really TEXT will cause bugs.

Also help to have cleaner code in onmessage in my opinion.

One of the power of binary is saving bandwith when dealing with numeric data with same schema : 
pos:x=2000000,y=2000000,z=2000000 ( 33 bytes )
opcodeintintint ( with opcode of 1 bytes = 13 bytes )
with homemade binary converter.

**Comment by titansoftime** [comment]
I see that the new release supports binary messaging. Are there any examples or docs on this. I am very interested in this feature but am not experienced enough to know how to send or receive (including the js) messages.

**Comment by cboden** [comment]
http://socketo.me/docs/migration-3
