### ISSUE TITLE
example of basic setup to serve normal php pages and web sockets

### ISSUE THREAD

**Issue by digininja** [ratchetphp/Ratchet#407]
I'm looking for a basic example of how to run a server that will do both normal HTTP requests and web sockets. I've seen a few examples that claim to work but running them up and trying to view HTML pages results in a "400 Bad Request" error which implies that the server is only parsing web socket requests and not HTTP requests.

**Comment by cboden** [comment]
While Ratchet wasn't meant to be a full fledged HTTP server it is possible because WebSockets are built on top of the HTTP protocol. I don't know of any tutorials to do so but you would use the [HttpServer](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/HttpServer.php) and probably [Router](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/Router.php) to do so. 

I would recommend taking a look at [App](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/App.php#L135) to see how it could be done. You could just use app and pass classes that implement [HttpServerInterface](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/HttpServerInterface.php) for HTTP requests and [WsServer objects](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php) for WebSockets.

**Comment by digininja** [comment]
That sounds interesting. It was only to investigate a specific issue which
has gone now but from this reply I'm interested to see if I can do it.
