### ISSUE TITLE
[0.4.x] How to get cookies on the connection?

### ISSUE THREAD

**Issue by dschissler** [ratchetphp/Ratchet#427]
https://github.com/perchlayer/webird/blob/master/app/phalcon/modules/cli/library/Chat.php#L41

`PHP Notice:  Undefined property: stdClass::$request in /opt/webird/app/phalcon/modules/cli/library/Chat.php on line 44`

This works on 0.3 but it no longer does on 0.4.x-dev.  Is it implemented or did something change at Guzzle.  I look at sources and documentation in Ratchet and Guzzle but I can't figure out if it changed or not yet implemented.

**Comment by cboden** [comment]
In 0.4 there are a few changes in this area to be aware of:
* There is a clearer separation of protocols, so request is no longer attached to WebSocket
* The Guzzle API has been replaced with PSR-7
* There is no cookie parser due to the previous bullet point

So what does that mean? Your code will need to look a bit more like this:
```php
$cookies = $conn->httpRequest->getHeader('Cookie');
```

Next, you will need to parse it. I haven't done much research into this you could look into [dflydev/dflydev-fig-cookies](https://github.com/dflydev/dflydev-fig-cookies)

**Comment by arosolino** [comment]
If you are using [guzzle/guzzle](https://github.com/guzzle/guzzle) 6.x you can do something like:

```php
$cookiesHeader = $conn->httpRequest->getHeader('Cookie');
if(count($cookiesHeader)) {
	$cookies = \GuzzleHttp\Cookie\SetCookie::fromString(current($cookiesHeader))->toArray();
	if (array_key_exists('PHPSESSID', $cookies)) {
		// PHPSESSID exists
	}
	else {
		// PHPSESSID does not exit
	}
}
else {
	// No cookie header
}
```

**Comment by dschissler** [comment]
@arosolino This works and I like using Guzzle since it is already included in the vendor directory.

Should we leave this open until the 0.4 docs are made and the new version is released?

**Comment by hayden-t** [comment]
whats the best way to parse the cookies now ?
`$cookies = $conn->httpRequest->getHeader('Cookie');`

**Comment by hayden-t** [comment]
after adding use GuzzleHttp\Psr7\Header; a top of file,

```
if($cookiesHeader = $conn->httpRequest->getHeader('Cookie')){

			$cookies = Header::parse($cookiesHeader);
			if($cookies && isset($cookies[0]['PHPSESSID'])){
				$cookie = $cookies[0]['PHPSESSID'];
				echo "Cookie found ".$cookie;
			}
		}
```
