### ISSUE TITLE
Firing up the chat-server.php automatically in windows environment

### ISSUE THREAD

**Issue by whimsicaldreamer** [ratchetphp/Ratchet#442]
How should I start up the chat-server.php in windows environment as supervisord is for *nix environment.

**Comment by kohenkatz** [comment]
You can register it as a Windows Service. There are multiple ways to do this:

 - Hand-edit the registry (**not recommended**)
 - If you have Visual Studio, use `installutil.exe` from the Visual Studio Command Line
 - Follow the instructions from [Tomcat](https://tomcat.apache.org/tomcat-7.0-doc/windows-service-howto.html).
 - Use a 3rd-party tool, such as [SrvMan](http://tools.sysprogs.org/srvman/)

**Comment by whimsicaldreamer** [comment]
And on a public server?

**Comment by kohenkatz** [comment]
Either you can register a service on the server, or you can't. If you can, I have listed options for how to do it. If you can't do any of the listed options, you likely need to find another server on which you can do them.

Note that if you are on a server which is running [Enkompass](https://web.archive.org/web/20120507204449/http://www.cpanel.net/windows/overview.html) or some similar hosting management platform, you may be able to configure it in the hosting management control panel. I can't help you with that.

If you are on Microsoft Azure, you can also [create a service through the management tools](https://alexandrebrisebois.wordpress.com/2015/02/22/lift-and-shift-of-a-windows-service-to-microsoft-azure/).

**Comment by whimsicaldreamer** [comment]
How can I understand on what it is running?

**Comment by whimsicaldreamer** [comment]
It would be nice if there was something inside the lib to fire up the server on its own.

**Comment by kohenkatz** [comment]
Here's another site I found with more information: http://stackoverflow.com/a/7939663/829970

There's no point in having something inside this library that you can just run to start up a server because you need to implement the actual logic as part of your own application.

If you want to add an example of using a Windows Service to the documentation, I think you could submit a Pull Request to [the documentation on the website](https://github.com/ratchetphp/socketo.me/blob/master/views/docs/deploy.html.twig). Unfortunately, I don't have time to write up the instructions right now.

**Comment by whimsicaldreamer** [comment]
I tried implementing many ways of starting up the server but either it doesn't start up or it starts and shuts down automatically. One example is over here http://stackoverflow.com/q/38290749/3697102
