### ISSUE TITLE
How to use both chat & server push notification servers in single/same server

### ISSUE THREAD

**Issue by TonyStark001** [ratchetphp/Ratchet#544]
However I have followed the tutorial guided in [socketo.me](http://socketo.me/docs).Both chat(HEllo World) & Push notification tutorial works fine independently. Is there any way to combine Chat & push notification servers into single server ?Any help would be appreciated.

**Comment by halfer** [comment]
That's rather a broad question. I wonder, since issue trackers are more for bug reporting, could you add your question to Stack Overflow, Reddit, or some community that focusses on helping on the design side of things? You may wish to add more detail, otherwise several rounds of clarification may become necessary.

**Comment by cboden** [comment]
Closing unless further information is provided.
