### ISSUE TITLE
Load balancing. 

### ISSUE THREAD

**Issue by MUmer1124** [ratchetphp/Ratchet#622]
Hi all.

I implement web socket server over Ratchet lib working fine with small amount to connections.
But we need to dedicated connections required 1500 figure then in the case server fall down & stop respond after 600 connections received.

For the above problem, we have an solution, please follow & then suggested me how it is possible.

1. Implement web socket server.
2. Use Haproxy to enable load balancer techniques to scalable
3. Implement Distributed cache (Redis) to share amony different instances running by load balancer.
In Redis cache we store connection objects which returns when new connection established. Implement a logic forward message to right socket.
See below snapshot, It write only to give an rough idea.

![1519972656659](https://user-images.githubusercontent.com/32255353/36886438-34c1326c-1e0e-11e8-9e1f-cbdc80a9c823.JPEG)

**Comment by andreybolonin** [comment]
https://github.com/andreybolonin/RatchetMultiInstance
We tested NGINX (as load balancer) with pool of Ratchet serves (WampServer)

**Comment by MUmer1124** [comment]
@andreybolonin Glad to hear from your response. I'll check it later. Thank you very much. 👍

**Comment by Mecanik** [comment]
Too complicated and bad idea, trust me. Just setup multiple servers and use a commercial LB or NGINX if you know how to setup, and connect to all the servers at once.

Reason why I say this, because I am working in production and commercial environment and this was the only way to make sure the servers are always up and from my tests I got even close to 100000 concurrent connections.

**Comment by mbonneau** [comment]
Closed due to inactivity.
