### ISSUE TITLE
Setting up a Push server on existing PHP code

### ISSUE THREAD

**Issue by him2016** [ratchetphp/Ratchet#644]
Hi,
I'm new to the Ratchet framework and facing some issue understanding how the architecture is designed. I have set up a basic Ratchet server and webSocket connection is being established from an Android client. Now, I have another PHP server that takes care of existing functionalities. I want to integrate both of these. So, the code base can be same or I would have to setup the Ratchet codebase as a separate application. 
Another issue is that how would I setup push messages from existing server. Would I have to run another PHP script on the Ratchet server or this would be sufficient?

Sorry if these questions sound naive, but pls help me..
Thanks,

**Comment by TheDigitalOrchard** [comment]
A WebSocket connection stays open between a client (web browser) and the server, unlike traditional web application that establish a fresh connection on each request.

In a traditional website setup, the following happens:

1) A browser sends a request to a server.
2) The server and browser confirm this request (handshake).
3) The server processes the request, and then sends the response.
4) The connection is closed.

The web is naturally a stateless environment, which is why we add client-side cookies, and server-side sessions to maintain (remember) state.

WebSockets maintains a connection between the server and connected clients. Basically, with a connection established, the server can send messages to all connected clients at any time. The request process can begin at the server.

Here's how it looks:

1) The client (browser) request a WebSocket connection with the server.
2) The server receives the request and adds the client to a list.
3) The connection remains open, with the server aware of all connected clients.
4) Messages can be sent back-and-forth between client and server.
5) The client or server can 'close' the connection at any time.

In order to involve a second server, you'd likely need some kind of server-to-server communication channel, and then the Ratchet server sends any notifications that it becomes aware of. That's all I can suggest without knowing more about your needs and setup.

Maybe give us a block-diagram showing your desired setup?

**Comment by mbonneau** [comment]
Closed for inactivity.

@him2016 This majority scenario is the [example pusher](http://socketo.me/docs/push) project.
