### ISSUE TITLE
WsServer and SessionProvider

### ISSUE THREAD

**Issue by ShuyqcK** [ratchetphp/Ratchet#668]
Hi, i have the same problem as #643 (https://github.com/ratchetphp/Ratchet/issues/643)
```php
  $myMessaging = new myMessaging();
  $session =  new SessionProvider($myMessaging, new Handler\NativeFileSessionHandler());
  $wsServer = new WsServer($session);
  $httpServer = new HttpServer($wsServer);
  $server = IoServer::factory($httpServer, 8010, '0.0.0.0');
  $server->run();
```
And if i pass the `SessionProvider` directly into the `HttpServer` my websocket request never ends and _onOpen_ does not run

There is a reason why the `WsServer` does not pass the _$request_ attribute in _onOpen_?

**Comment by cboden** [comment]
> There is a reason why the WsServer does not pass the $request attribute in onOpen?

It's [assigned to the connection object](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php#L112) when the request is made. I don't recall why this decision was made, but you're able to access the request via `$conn->httpRequest`. 

--- 

The order of your code will not work here. Because `WsServer` doesn't pass the request to onOpen it can't decorate Session.

```php
  $myMessaging = new myMessaging();
  $wsServer = new WsServer($myMessaging);
  $session =  new SessionProvider($wsServer, new Handler\NativeFileSessionHandler());
  $httpServer = new HttpServer($session);
  $server = IoServer::factory($httpServer, 8010, '0.0.0.0');
  $server->run();
```

---

> And if i pass the SessionProvider directly into the HttpServer my websocket request never ends and onOpen does not run

From the [documentation](http://socketo.me/docs/sessions):
> The SessionProvider will not work with any of the Native* session handlers
