### ISSUE TITLE
Sending a message directly to resourceID

### ISSUE THREAD

**Issue by TechOverflow** [ratchetphp/Ratchet#714]
Is there a way to send a message directly to one client?
Something like this 

```
<?php

use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use Ratchet\WebSocket\WsServerInterface;

require 'vendor/autoload.php';
require_once 'db.php';

$to = 119; // hard-coded id, not using database yet

$msg = json_encode(array("test" => "test"));

class Sender implements MessageComponentInterface, ConnectionInterface {

    public function send(ConnectionInterface $to, $msg) {
        $client = $this->clients[$to];
        $client->send($msg);
    }

}

Sender::send($to, $msg);
```

The server instance is already created and opening/closing/receiving in a different script. Resource IDs are stored to and updated in a database.

**Comment by agentd00nut** [comment]
There's probably a few ways to do this.  Simple but not that great way would be to iterate over $this->clients comparing each resourceId to your $to variable.
```        
foreach ($this->clients as $client) {
            if ($to == $client->resourceId) {
                $client->send($msg);
            }
        }
```

When the client connects its being pushed into a `SplObjectStorage`.  The `ConnectionInterface`'s `resourceId` is completely separate from this object storage.

Part of SplObjectStorage is that when you set an object into it you can also associate that object with some data.  You could set the data to the objects resourceId and then iterate over the clients and get the resourceId from whats stored as that objects data instead of the object itself.... this would, at best, be marginally faster, and is less readable.
```
for($this->clients as $client){
  if($to == $this->clients[$client]){ $client->send($msg); }
}
```

If you really can't get your sender the actual object of the ClientInterface you want to send the message to and are stuck using only the ids.  Then i would consider just making another array and when a client connects you store the ClientInterface into this other array, key'd on their resourceId.
Obviously now you're managing two storages and that's tedious.

**Comment by TechOverflow** [comment]
@agentd00nut I appreciate the tip, this seems like it should work. The problem I'm having, probably due to my lack of OOP experience is how to access the Chat class.

Using the [http://socketo.me/docs/hello-world](http://socketo.me/docs/hello-world) example, I would add this to `class Chat`

```
public function test() {
    return $this->clients;
}
```

but how can I call the function from outside the class?
If I use the below script in another .php file, which requires Chat.php

```
require_once 'Chat.php'
$var = new Chat();
$foo = $var->test();
var_dump($foo);
```

returns `object(SplObjectStorage)#2 (1) { ["storage":"SplObjectStorage":private]=> array(0) { } }`

I guess this is because this is another instance of `Chat` and the `SplObjectStorage` is blank.
Is there a correct way of getting the array from the class run by the $server?

**Comment by DevilCheyp** [comment]
I think you should try - http://socketo.me/docs/push
It helped me!

**Comment by TechOverflow** [comment]
What I ended up doing was creating a unique WS client that acts as a middleman between any HTML based app and the running WS server. The WS client sends a message to the server, the server `onMessage` decides who to repeat the message to, and the client disconnects. I may be adding some type of wait for receiving the re-routed reply back.

**Comment by lucaele** [comment]
Ratchet for OCCP-J?
i'm interesting too.

My problem is on handshake response from ratchet.
Any idea?
