### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'MyApp\Chat' not found in /var/www/bin/chat-server.php:10

### ISSUE THREAD

**Issue by gareth41** [ratchetphp/Ratchet#769]
Perhaps make the documentation clearer at http://socketo.me/docs/hello-world as for people like myself who are new to this, trying to get this example to work is like trying to catch water with a sieve.

**Comment by cboden** [comment]
It looks like the error occurred because the Chat class was not found, which could either be a typo, the namespace wasn't registered, or something else. 

As the documentation states, I would recommend becoming familiar with [PSR-4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md) and [composer](https://getcomposer.org). These are two very common tools in the PHP ecosystem and an understanding of them would assist your troubleshooting.
