### ISSUE TITLE
Ping pong incorrect frame mask

### ISSUE THREAD

**Issue by vladozilo** [ratchetphp/Ratchet#782]
Hi, 

I have running server by App class with routes implements Ratchet\MessageComponentInterface. Some clients works fine but there is one device that connect, send and receive message but after that it try to send ping (maybe with binnary data) but it is disconnected by Ratchet because it detected an incorrect frame mask. Could you tell me please whats the problem?

Thank you

**Comment by elovin** [comment]
A working example and logs would help

**Comment by vladozilo** [comment]
I put example and logs below but at the beginning i would like to say it is partially running when I changed $expectMask to false in creating new instance of MessageBuffer here:
[https://github.com/ratchetphp/Ratchet/blob/57721e1f184f9e29378fc5363867c47ddda743fd/src/Ratchet/WebSocket/WsServer.php#L136](url)
If $expectMask is set to true, incorrect frame mask is thrown from MessageBuffer.php

server
```
$app = new RatchetApp($host, $port, '0.0.0.0');
$app->route('/test', new TestController(), [ '*' ]);

foreach ($app->routes->all() as $route) {
  $this->info('socket run on ' . $host . ':' . $port . '' . $route->getPath());
}
$app->run();
```

controller
```
class TestController extends Controller implements MessageComponentInterface, WsServerInterface
{
...
    public function onOpen(ConnectionInterface $conn)
    {
        echo "New conn {$conn->resourceId}\n";
    }

    public function onMessage(ConnectionInterface $from, $message)
    {
 echo "onMessage {$from->resourceId}\n";
$from->send($message);
    }
...
```

This is part of log
![Screenshot 2020-02-14 at 20 57 45](https://user-images.githubusercontent.com/10502206/74563245-aade9e80-4f6c-11ea-9f86-0b5b337395cc.png)

**Comment by vladozilo** [comment]
Any ideas?

**Comment by cboden** [comment]
What is the client application/library you are using that is being disconnected?

**Comment by cboden** [comment]
As per section [5.1 of the RFC6455 protocol](https://tools.ietf.org/html/rfc6455#section-5.1):
> To avoid confusing network intermediaries (such as
   intercepting proxies) and for security reasons that are further
   discussed in Section 10.3, a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).  (Note
   that masking is done whether or not the WebSocket Protocol is running
   over TLS.)  The server MUST close the connection upon receiving a
   frame that is not masked.

Ratchet is following the spec accordingly here, the client you're using to connect is not. 

The reason `MessageBuffer` has an `$expectMask` parameter is because it handles the protocol for both client and server; where going the other direction, the client should not be receiving masked frames.

**Comment by vladozilo** [comment]
@cboden Thnak you so much. I don't know what is the client library because it is hardware(charger) which connects to server via websocket.
