### ISSUE TITLE
Documentation not available (http://socketo.me/)

### ISSUE THREAD

**Issue by nkoepke** [ratchetphp/Ratchet#972]
The documentation on http://socketo.me/ is not available anymore due to the host server since 26.06.2022

**Comment by Ale3470** [comment]
### Any predictions on when the documentation comes back?

**Comment by qiulang** [comment]
BTW any chance to support https for the new site ?

**Comment by HenriqueVS600** [comment]
**Too bad I was creating a project using the library**

**Comment by cboden** [comment]
> Any predictions on when the documentation comes back?

**Next week when I'm back from my friend's wedding**

---

> BTW any chance to support https for the new site ?

Definitely want to do this!

---

> Too bad I was creating a project using the library

Too bad the website isn't open sourced and hosted on GitHub. [Oh wait, it is](http://github.com/ratchetphp/socketo.me)

**Comment by seunex17** [comment]
Any update on the host resolution please. This is kind of flu straing. 😡

**Comment by cboden** [comment]
> Any update on the host resolution please. This is kind of flu straing. 😡

# Next week when I'm back from my friend's wedding

**Comment by clue** [comment]
@nkoepke Thank you for reporting!

As @cboden already pointed out, we'll fix this as soon as time allows. We understand it's frustrating the site doesn't work at the moment, so we'll do our best to fix this in a timely manner. I'll lock this discussion for now to focus on getting this done rather than replying to each ping.

In the meantime, you may use the web archive as linked above: https://web.archive.org/web/20220626151542/http://socketo.me/

We'll keep this ticket updated as we make progress, expect an update the next couple of days.

**Comment by cboden** [comment]
Site has been back up for a few days now. I didn't get SSL in yet as I was focusing on just getting it working again.
